###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################

replicaCount: 1

image:
    sipOrchestrator:
        image: "ibmcom/voice-gateway-so"
        containerName: "vgw-sip-orchestrator"
    mediaRelay:
        image: "ibmcom/voice-gateway-mr"
        containerName: "vgw-media-relay"
    tag: "latest"
    pullPolicy: "Always"

# refer to enable recording section in readme for more details
mediaRelayEnvVariables:
    enableRecording: "false"
