###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}
  creationTimestamp: 
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" 
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: vgw
  template:
    metadata:
      creationTimestamp: 
      labels:
        service: vgw
    spec:
      volumes:
      {{- if eq .Values.mediaRelayEnvVariables.enableRecording "true" }}
      - persistentVolumeClaim:
          claimName: recordings
        name: recordings
      {{- end}}
      - name: tenantconfig
        secret:
          secretName: tenantconfig
          items:
          - key: tenantConfig.json
            path: tenantConfig.json
      hostNetwork: true
      imagePullSecrets:
      - name: admin.registrykey
      containers:
      - name: {{ .Values.image.mediaRelay.containerName }}
        image: "{{ .Values.image.mediaRelay.image }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        env:
        - name: SDP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ENABLE_RECORDING
          value: "{{ .Values.mediaRelayEnvVariables.enableRecording }}"
        - name: RTP_UDP_PORT_RANGE
          value: 16384-16394
        - name: CLUSTER_WORKERS
          value: '0'
        - name: MEDIA_RELAY_LOG_LEVEL
          value: DEBUG
        - name: MEDIA_RELAY_WS_PORT
          value: '8080'
        resources: {}
        {{- if eq .Values.mediaRelayEnvVariables.enableRecording "true" }}
        volumeMounts:
        - name: recordings
          mountPath: "/vgw-media-relay/recordings"
        {{- end}}
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      - name: {{ .Values.image.sipOrchestrator.containerName }}
        image: "{{ .Values.image.sipOrchestrator.image }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5060
          hostPort: 5060
          protocol: TCP
        - containerPort: 5060
          hostPort: 5060
          protocol: UDP
        env:
        - name: SIP_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MEDIA_RELAY_HOST
          value: localhost:8080
        - name: SIP_PORT
          value: '5060'
        - name: ENABLE_AUDIT_MESSAGES
          value: 'true'
        - name: ENABLE_TRANSCRIPTION_AUDIT_MESSAGES
          value: 'true'
        - name: LOG_LEVEL
          value: all
        - name: MULTI_TENANT_CONFIG_FILE
          value: "/tenantconfig/tenantConfig.json"
        resources: {}
        volumeMounts:
        - name: tenantconfig
          mountPath: "/tenantconfig/tenantConfig.json"
          subPath: tenantConfig.json
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status: {}
