###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################

{{- if eq .Values.mediaRelayEnvVariables.enableRecording "true" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: recordings
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" 
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteMany
{{- end }}